### ISSUE TITLE
encoder weights

### ISSUE THREAD

**Issue by sebastiangonsal** [e-lab/ENet-training#62]
Did you try freezing the encoder weights while training the entire model in second step?

**Comment by codeAC29** [comment]
@sebastiangonsal Is it different than #61 closed by you?

**Comment by sebastiangonsal** [comment]
Yes. This time the q is whether during your experimentation you tried freezing encoder weights and how bad were the results :) (Since you didn't freeze them in the final paper)

**Comment by codeAC29** [comment]
You set your model in `evaluate()` mode while evaluating (experimentation) ([here](https://github.com/e-lab/ENet-training/blob/master/train/test.lua#L48)). Updating weights during inference does not even make sense unless you want to do online learning. So, we do freeze the weights of both encoder and decoder while evaluation and we have not mentioned otherwise in our paper. If we have said something like that in our paper, then please point it out so that we can fix that mistake.

**Comment by sebastiangonsal** [comment]
I actually did not mean evaluation by "experimentation". I meant whether you experimented freezing already trained encoder weights while training the entire model and what was the performance of the resulting model.

**Comment by sebastiangonsal** [comment]
Closing this.
